<?php

/**
 * @file
 * This file will count whether any movie node is present or not.
 */

/**
 * Helper function to determine if a user has movie posts already.
 *
 * @return string
 *   Count of blog posts.
 */
function movie_counter($account = NULL) {
  $query = \Drupal::entityQuery('node')
    ->condition('type', 'movie')
    ->condition('status', 1)
    ->accessCheck(TRUE);
  if ($account !== NULL) {
    $query->condition('uid', $account->id());
  }
  return $query->count()
    ->execute();
}
