# Schema for the configuration files of the budget_menu module.
budget_menu.settings:
  type: config_object
  label: 'budget_menu settings'
  mapping:
    example:
      type: string
      label: 'Example'
