<?php
use Drupal\config_form\Form\ConfigForm;

/**
 * @file
 * This file is responsible for mentioning the hook.
 */

/**
 * Implements hook_mail() for Drupal\Core\Mail\MailManagerInterface.
 */
function config_form_mail($key, &$message, $params)
{
  // This mentioned key is present in the config form. doMail() function called
  // this hook for sending the mail.
  if ($key === ConfigForm::MAIL_KEY) {
    $message['from'] = \Drupal::config('system.site')->get('mail');
    $message['subject'] = $params['subject'];
    $message['body'][] = $params['body'];
  }
}