config_form.admin_api_form:
  path: '/admin/config-form'
  defaults:
    _title: 'Fill the config form'
    _form: 'Drupal\config_form\Form\ConfigForm'
  requirements:
    _permission: 'administer'

config_form.generate_login_link:
  path: '/admin/config/system/generate-login-link'
  defaults:
    _title: 'Generate login link'
    _form: 'Drupal\config_form\Form\GenerateLoginLink'
  requirements:
    _permission: 'administer'         
