# Schema for the configuration files of the Welcome Block module.
welcome_block.settings:
  type: config_object
  label: 'Welcome Block settings'
  mapping:
    example:
      type: string
      label: 'Example'
