<?php

/**
 * @file
 * This hook will be used to add the custom theme.
 */

/**
 * Implements hook_theme().
 */
function custom_rgb_theme($existing, $type, $theme, $path) {
  return [
    'custom_rgb_color_picker' => [
      'template' => 'custom-rgb-color-picker',
      'variables' => [
        'content' => NULL,
        'color' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_multiple_field_remove_button_field_types_alter().
 */
function custom_rgb_multiple_field_remove_button_field_types_alter(array &$fieldTypes): void {
  $fieldTypes[] = "custom_rgb_field";
}
