movie.movie.*:
  type: config_entity
  label: Movie
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string

movie.awardmovie.*:
  type: config_entity
  label: AwardMovie
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string
