<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_form_alter().
 */
function welcome_block_form_alter(array &$form, FormStateInterface $form_state, string $form_id) {
  if ($form_id == 'user_login_form') {
     $form['#submit'][] = 'welcome_block_submit_handler';
  }
}

/**
 * This fucntion forward user to the custom welcome page.
 * 
 * @param array $form
 *   This array contains the form strcture.
 * @param FormStateInterface $form_state
 *   This tracks the different state of the form.
 * 
 * @return void
 *   Instead of returning value this function redirect the page.
 */
function welcome_block_submit_handler(array $form, FormStateInterface $form_state) {
  $url = Url::fromRoute('custom_welcome_page.routing');
  $form_state->setRedirectUrl($url);
}

/**
 * Implements hook_theme().
 */
function welcome_block_theme($existing, $type, $theme, $path) {
  return [
    'hcl_events_block' => [
      'template' => 'hcl-events-block',
      'variables' => [
        'content' => NULL,
      ],
    ],
  ];
}

