<?php

/**
 * @file
 * This will be used to create a new bundle in node.
 */

use Drupal\node\Entity\NodeType;

/**
 * Implements hook_install().
 */
function movie_bundle_update_11111() {
  // Create the "movie" bundle for the "node" entity type.
  $node_type = NodeType::create([
    'type' => 'movie',
    'name' => 'Movie',
    'description' => 'Movie content type',
    'base' => 'node_content',
    'display_submitted' => FALSE,
  ]);
  $node_type->save();
}
