<?php

/**
 * @file
 * Primary module hooks for budget_menu module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_view().
 */
function budget_menu_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->getEntityTypeId() === 'node' && $entity->bundle() === 'movie') {

    // Get the budget amount from the config form.
    $config = \Drupal::config('budget_menu.settings');
    $budget_amount = $config->get('budget_friendly_amount');

    // Get the budget amount from the node field.
    $node_budget_amount = $entity->get('field_price')->value;

    if ($node_budget_amount) {

      // Compare the budget amounts and set the corresponding text.
      if ($budget_amount > $node_budget_amount) {
        $status = 'The movie is under budget';
        $color = 'yellow';
      }
      elseif ($budget_amount < $node_budget_amount) {
        $status = 'The movie is over budget';
        $color = 'red';
      }
      else {
        $status = 'The movie is within budget';
        $color = 'green';
      }

      $build['budget_status'] = [
        '#type' => 'html_tag',
        '#tag' => 'p',
        '#value' => $status,
        '#attributes' => [
          'style' => 'background-color:' . $color . ';',
        ],
      ];
    }

    $build['budget_status'] = [
      '#type' => 'html_tag',
      '#tag' => 'p',
      '#value' => $status,
      '#attributes' => [
        'style' => 'background-color:' . $color . ';',
      ],
    ];
  }

}

/**
 * Implements hook_toolbar_alter().
 */
function budget_menu_toolbar_alter(&$items) {
  $items['administration']['#attached']['library'][] = 'budget_menu/budget_menu';
}
